SELECT V.FLAVOR
  FROM 
(SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) TOTAL_ORDER
  FROM FIRST_HALF F, JULY J
 WHERE F.FLAVOR = J.FLAVOR
 GROUP BY F.FLAVOR
 ORDER BY TOTAL_ORDER DESC) V
 LIMIT 3;