SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (MAX_SIZE.MAX_COLONY - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_SIZE
ON YEAR(e.DIFFERENTIATION_DATE) = MAX_SIZE.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
