SELECT f.id, n.FISH_NAME, f.LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
WHERE f.LENGTH = (
    SELECT MAX(f2.LENGTH)
    FROM FISH_INFO f2
    WHERE f2.FISH_TYPE = f.FISH_TYPE
)
ORDER BY f.ID ASC;